name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment7-buildroot
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Run full test
        run: ./full-test.sh
